/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as CxcRouteImport } from './routes/cxc'
import { Route as CxpRouteImport } from './routes/cxp'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as DocTipoIdRouteImport } from './routes/doc.$tipo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CxcRoute = CxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => rootRouteImport,
} as any)
const CxpRoute = CxpRouteImport.update({
  id: '/cxp',
  path: '/cxp',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const DocTipoIdRoute = DocTipoIdRouteImport.update({
  id: '/doc/$tipo/$id',
  path: '/doc/$tipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/inventario': typeof InventarioRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/tesoreria': typeof TesoreriaRoute
  '/ventas': typeof VentasRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/inventario': typeof InventarioRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/tesoreria': typeof TesoreriaRoute
  '/ventas': typeof VentasRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/inventario': typeof InventarioRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/tesoreria': typeof TesoreriaRoute
  '/ventas': typeof VentasRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cxc'
    | '/cxp'
    | '/inventario'
    | '/productos'
    | '/proveedores'
    | '/tesoreria'
    | '/ventas'
    | '/doc/$tipo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cxc'
    | '/cxp'
    | '/inventario'
    | '/productos'
    | '/proveedores'
    | '/tesoreria'
    | '/ventas'
    | '/doc/$tipo/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/compras'
    | '/cxc'
    | '/cxp'
    | '/inventario'
    | '/productos'
    | '/proveedores'
    | '/tesoreria'
    | '/ventas'
    | '/doc/$tipo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  CxcRoute: typeof CxcRoute
  CxpRoute: typeof CxpRoute
  InventarioRoute: typeof InventarioRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  TesoreriaRoute: typeof TesoreriaRoute
  VentasRoute: typeof VentasRoute
  DocTipoIdRoute: typeof DocTipoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cxc': {
      id: '/cxc'
      path: '/cxc'
      fullPath: '/cxc'
      preLoaderRoute: typeof CxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cxp': {
      id: '/cxp'
      path: '/cxp'
      fullPath: '/cxp'
      preLoaderRoute: typeof CxpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$tipo/$id': {
      id: '/doc/$tipo/$id'
      path: '/doc/$tipo/$id'
      fullPath: '/doc/$tipo/$id'
      preLoaderRoute: typeof DocTipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  CxcRoute: CxcRoute,
  CxpRoute: CxpRoute,
  InventarioRoute: InventarioRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  TesoreriaRoute: TesoreriaRoute,
  VentasRoute: VentasRoute,
  DocTipoIdRoute: DocTipoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
