/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgenciasRouteImport } from './routes/agencias'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as CpoRouteImport } from './routes/cpo'
import { Route as CrucesRouteImport } from './routes/cruces'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as CxcRouteImport } from './routes/cxc'
import { Route as CxpRouteImport } from './routes/cxp'
import { Route as DestinosRouteImport } from './routes/destinos'
import { Route as EmbarquesRouteImport } from './routes/embarques'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ListasRouteImport } from './routes/listas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TesoreriaRouteImport } from './routes/tesoreria'
import { Route as TransportistasRouteImport } from './routes/transportistas'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as PortalIdRouteImport } from './routes/portal.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCpoAttachmentIdRouteImport } from './routes/api/cpo-attachment.$id'
import { Route as DocTipoIdRouteImport } from './routes/doc.$tipo.$id'
import { Route as EtiquetasLotesPoIdRouteImport } from './routes/etiquetas.lotes.$poId'
import { Route as EtiquetasPalletsPoIdRouteImport } from './routes/etiquetas.pallets.$poId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciasRoute = AgenciasRouteImport.update({
  id: '/agencias',
  path: '/agencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CpoRoute = CpoRouteImport.update({
  id: '/cpo',
  path: '/cpo',
  getParentRoute: () => rootRouteImport,
} as any)
const CrucesRoute = CrucesRouteImport.update({
  id: '/cruces',
  path: '/cruces',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const CxcRoute = CxcRouteImport.update({
  id: '/cxc',
  path: '/cxc',
  getParentRoute: () => rootRouteImport,
} as any)
const CxpRoute = CxpRouteImport.update({
  id: '/cxp',
  path: '/cxp',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinosRoute = DestinosRouteImport.update({
  id: '/destinos',
  path: '/destinos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbarquesRoute = EmbarquesRouteImport.update({
  id: '/embarques',
  path: '/embarques',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ListasRoute = ListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoreriaRoute = TesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportistasRoute = TransportistasRouteImport.update({
  id: '/transportistas',
  path: '/transportistas',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIdRoute = PortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCpoAttachmentIdRoute = ApiCpoAttachmentIdRouteImport.update({
  id: '/api/cpo-attachment/$id',
  path: '/api/cpo-attachment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocTipoIdRoute = DocTipoIdRouteImport.update({
  id: '/doc/$tipo/$id',
  path: '/doc/$tipo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetasLotesPoIdRoute = EtiquetasLotesPoIdRouteImport.update({
  id: '/etiquetas/lotes/$poId',
  path: '/etiquetas/lotes/$poId',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetasPalletsPoIdRoute = EtiquetasPalletsPoIdRouteImport.update({
  id: '/etiquetas/pallets/$poId',
  path: '/etiquetas/pallets/$poId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencias': typeof AgenciasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cpo': typeof CpoRoute
  '/cruces': typeof CrucesRoute
  '/cuentas': typeof CuentasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/destinos': typeof DestinosRoute
  '/embarques': typeof EmbarquesRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/settings': typeof SettingsRoute
  '/tesoreria': typeof TesoreriaRoute
  '/transportistas': typeof TransportistasRoute
  '/ventas': typeof VentasRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cpo-attachment/$id': typeof ApiCpoAttachmentIdRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
  '/etiquetas/lotes/$poId': typeof EtiquetasLotesPoIdRoute
  '/etiquetas/pallets/$poId': typeof EtiquetasPalletsPoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencias': typeof AgenciasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cpo': typeof CpoRoute
  '/cruces': typeof CrucesRoute
  '/cuentas': typeof CuentasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/destinos': typeof DestinosRoute
  '/embarques': typeof EmbarquesRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/settings': typeof SettingsRoute
  '/tesoreria': typeof TesoreriaRoute
  '/transportistas': typeof TransportistasRoute
  '/ventas': typeof VentasRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cpo-attachment/$id': typeof ApiCpoAttachmentIdRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
  '/etiquetas/lotes/$poId': typeof EtiquetasLotesPoIdRoute
  '/etiquetas/pallets/$poId': typeof EtiquetasPalletsPoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencias': typeof AgenciasRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cpo': typeof CpoRoute
  '/cruces': typeof CrucesRoute
  '/cuentas': typeof CuentasRoute
  '/cxc': typeof CxcRoute
  '/cxp': typeof CxpRoute
  '/destinos': typeof DestinosRoute
  '/embarques': typeof EmbarquesRoute
  '/gastos': typeof GastosRoute
  '/inventario': typeof InventarioRoute
  '/listas': typeof ListasRoute
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/settings': typeof SettingsRoute
  '/tesoreria': typeof TesoreriaRoute
  '/transportistas': typeof TransportistasRoute
  '/ventas': typeof VentasRoute
  '/portal/$id': typeof PortalIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cpo-attachment/$id': typeof ApiCpoAttachmentIdRoute
  '/doc/$tipo/$id': typeof DocTipoIdRoute
  '/etiquetas/lotes/$poId': typeof EtiquetasLotesPoIdRoute
  '/etiquetas/pallets/$poId': typeof EtiquetasPalletsPoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencias'
    | '/clientes'
    | '/compras'
    | '/cpo'
    | '/cruces'
    | '/cuentas'
    | '/cxc'
    | '/cxp'
    | '/destinos'
    | '/embarques'
    | '/gastos'
    | '/inventario'
    | '/listas'
    | '/login'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/settings'
    | '/tesoreria'
    | '/transportistas'
    | '/ventas'
    | '/portal/$id'
    | '/api/auth/$'
    | '/api/cpo-attachment/$id'
    | '/doc/$tipo/$id'
    | '/etiquetas/lotes/$poId'
    | '/etiquetas/pallets/$poId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencias'
    | '/clientes'
    | '/compras'
    | '/cpo'
    | '/cruces'
    | '/cuentas'
    | '/cxc'
    | '/cxp'
    | '/destinos'
    | '/embarques'
    | '/gastos'
    | '/inventario'
    | '/listas'
    | '/login'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/settings'
    | '/tesoreria'
    | '/transportistas'
    | '/ventas'
    | '/portal/$id'
    | '/api/auth/$'
    | '/api/cpo-attachment/$id'
    | '/doc/$tipo/$id'
    | '/etiquetas/lotes/$poId'
    | '/etiquetas/pallets/$poId'
  id:
    | '__root__'
    | '/'
    | '/agencias'
    | '/clientes'
    | '/compras'
    | '/cpo'
    | '/cruces'
    | '/cuentas'
    | '/cxc'
    | '/cxp'
    | '/destinos'
    | '/embarques'
    | '/gastos'
    | '/inventario'
    | '/listas'
    | '/login'
    | '/productos'
    | '/proveedores'
    | '/reportes'
    | '/settings'
    | '/tesoreria'
    | '/transportistas'
    | '/ventas'
    | '/portal/$id'
    | '/api/auth/$'
    | '/api/cpo-attachment/$id'
    | '/doc/$tipo/$id'
    | '/etiquetas/lotes/$poId'
    | '/etiquetas/pallets/$poId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciasRoute: typeof AgenciasRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  CpoRoute: typeof CpoRoute
  CrucesRoute: typeof CrucesRoute
  CuentasRoute: typeof CuentasRoute
  CxcRoute: typeof CxcRoute
  CxpRoute: typeof CxpRoute
  DestinosRoute: typeof DestinosRoute
  EmbarquesRoute: typeof EmbarquesRoute
  GastosRoute: typeof GastosRoute
  InventarioRoute: typeof InventarioRoute
  ListasRoute: typeof ListasRoute
  LoginRoute: typeof LoginRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ReportesRoute: typeof ReportesRoute
  SettingsRoute: typeof SettingsRoute
  TesoreriaRoute: typeof TesoreriaRoute
  TransportistasRoute: typeof TransportistasRoute
  VentasRoute: typeof VentasRoute
  PortalIdRoute: typeof PortalIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCpoAttachmentIdRoute: typeof ApiCpoAttachmentIdRoute
  DocTipoIdRoute: typeof DocTipoIdRoute
  EtiquetasLotesPoIdRoute: typeof EtiquetasLotesPoIdRoute
  EtiquetasPalletsPoIdRoute: typeof EtiquetasPalletsPoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencias': {
      id: '/agencias'
      path: '/agencias'
      fullPath: '/agencias'
      preLoaderRoute: typeof AgenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpo': {
      id: '/cpo'
      path: '/cpo'
      fullPath: '/cpo'
      preLoaderRoute: typeof CpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruces': {
      id: '/cruces'
      path: '/cruces'
      fullPath: '/cruces'
      preLoaderRoute: typeof CrucesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cxc': {
      id: '/cxc'
      path: '/cxc'
      fullPath: '/cxc'
      preLoaderRoute: typeof CxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cxp': {
      id: '/cxp'
      path: '/cxp'
      fullPath: '/cxp'
      preLoaderRoute: typeof CxpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinos': {
      id: '/destinos'
      path: '/destinos'
      fullPath: '/destinos'
      preLoaderRoute: typeof DestinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embarques': {
      id: '/embarques'
      path: '/embarques'
      fullPath: '/embarques'
      preLoaderRoute: typeof EmbarquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listas': {
      id: '/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof ListasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoreria': {
      id: '/tesoreria'
      path: '/tesoreria'
      fullPath: '/tesoreria'
      preLoaderRoute: typeof TesoreriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportistas': {
      id: '/transportistas'
      path: '/transportistas'
      fullPath: '/transportistas'
      preLoaderRoute: typeof TransportistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$id': {
      id: '/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof PortalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cpo-attachment/$id': {
      id: '/api/cpo-attachment/$id'
      path: '/api/cpo-attachment/$id'
      fullPath: '/api/cpo-attachment/$id'
      preLoaderRoute: typeof ApiCpoAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$tipo/$id': {
      id: '/doc/$tipo/$id'
      path: '/doc/$tipo/$id'
      fullPath: '/doc/$tipo/$id'
      preLoaderRoute: typeof DocTipoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiquetas/lotes/$poId': {
      id: '/etiquetas/lotes/$poId'
      path: '/etiquetas/lotes/$poId'
      fullPath: '/etiquetas/lotes/$poId'
      preLoaderRoute: typeof EtiquetasLotesPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiquetas/pallets/$poId': {
      id: '/etiquetas/pallets/$poId'
      path: '/etiquetas/pallets/$poId'
      fullPath: '/etiquetas/pallets/$poId'
      preLoaderRoute: typeof EtiquetasPalletsPoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciasRoute: AgenciasRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  CpoRoute: CpoRoute,
  CrucesRoute: CrucesRoute,
  CuentasRoute: CuentasRoute,
  CxcRoute: CxcRoute,
  CxpRoute: CxpRoute,
  DestinosRoute: DestinosRoute,
  EmbarquesRoute: EmbarquesRoute,
  GastosRoute: GastosRoute,
  InventarioRoute: InventarioRoute,
  ListasRoute: ListasRoute,
  LoginRoute: LoginRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  ReportesRoute: ReportesRoute,
  SettingsRoute: SettingsRoute,
  TesoreriaRoute: TesoreriaRoute,
  TransportistasRoute: TransportistasRoute,
  VentasRoute: VentasRoute,
  PortalIdRoute: PortalIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCpoAttachmentIdRoute: ApiCpoAttachmentIdRoute,
  DocTipoIdRoute: DocTipoIdRoute,
  EtiquetasLotesPoIdRoute: EtiquetasLotesPoIdRoute,
  EtiquetasPalletsPoIdRoute: EtiquetasPalletsPoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
